# -*- coding: utf-8 -*-
"""pythonworkshop_260702_Olivia_regression_timecourse_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LvZwsxNG9ZDlGM8CIHE43vWfbrpyjv5b

## Prompt
 You are an experienced data scientist and Python developer. I want to analyse a time-series dataset using Google Colab and Python.

The dataset is stored as a CSV file named DailyDelhiClimateTest.csv.

The dataset contains the following columns (case-sensitive):

date (YYYY-MM-DD format)
meantemp
humidity
wind_speed
meanpressure

The date column contains daily timestamps, and all remaining variables are floating-point numerical values.

The objective is to perform time-series forecasting by predicting the future value of the meantemp variable using an XGBoost Regressor (XGBRegressor).

Before building the machine learning model, perform a comprehensive Exploratory Data Analysis (EDA) using both Sweetviz and ydata-profiling to assess the quality, completeness, and suitability of the dataset.

The notebook should:

Parse the date column correctly.
Check for missing values, duplicates, incorrect data types, and outliers.
Display descriptive statistics.
Visualise variable distributions.
Produce a correlation matrix.
Generate Sweetviz and ydata-profiling reports.

After completing the EDA:

Sort the data chronologically.
Create appropriate lag features for meantemp (for example, the previous 7 days).
Create any additional time-based features that may improve forecasting, such as day, month, or day of the week.
Split the data chronologically into training and testing datasets without randomly shuffling the observations.
Train an XGBRegressor to predict meantemp.

Evaluate the regression model using:

Mean Absolute Error (MAE)
Mean Squared Error (MSE)
Root Mean Squared Error (RMSE)
R² Score
Learning Curve

Produce the following visualisations:

Actual vs Predicted values
Residual Plot
Feature Importance
Learning Curve

Include clear comments explaining every major step so that the notebook can be used as a teaching resource for learning time-series machine learning using XGBoost.

Present the notebook as a complete Google Colab workflow divided into three clearly labelled sections:

Part 1

Install all required libraries.
Import the dataset.
Parse the date column.
Perform the complete EDA using Sweetviz and ydata-profiling.

Part 2

Perform feature engineering.
Create lag features.
Prepare the feature matrix and target variable.
Split the data chronologically.
Train the XGBoost regression model.

Part 3

Run the trained model on the test dataset.
Evaluate the model using MAE, MSE, RMSE, and R².
Display all requested plots.
Interpret the model's performance and discuss any evidence of overfitting or underfitting based on the learning curve.

Ensure that all code cells are fully executable in Google Colab and include explanatory comments suitable for someone learning XGBoost and time-series regression. Use TimeSeriesSplit where appropriate for cross-validation and learning-curve generation to preserve the temporal ordering of the data.

## Part 1. Install libraries, import dataset and perform EDA
"""

# ============================================================
# PART 1
# Install libraries, import dataset and perform EDA
# ============================================================

# ------------------------------------------------------------
# Install required libraries (Google Colab)
# ------------------------------------------------------------

pip install xgboost sweetviz ydata-profiling 

# ------------------------------------------------------------
# Import libraries
# ------------------------------------------------------------

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import sweetviz as sv
from ydata_profiling import ProfileReport

# Display settings
pd.set_option('display.max_columns', None)

# ------------------------------------------------------------
# Load dataset
# ------------------------------------------------------------
from google.colab import files

uploaded = files.upload()
df = pd.read_csv(
    "DailyDelhiClimateTrain.csv",
    parse_dates=["date"]
)

# View first rows
print("First five rows:")
display(df.head())

# Dataset information
print("\nDataset Information")
df.info()

# ------------------------------------------------------------
# Basic Data Quality Checks
# ------------------------------------------------------------

print("\nShape of dataset:")
print(df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

# ------------------------------------------------------------
# Descriptive Statistics
# ------------------------------------------------------------

print("\nDescriptive Statistics")
display(df.describe())

# ------------------------------------------------------------
# Check Date Range
# ------------------------------------------------------------

print("Earliest Date :", df["date"].min())
print("Latest Date   :", df["date"].max())

# ------------------------------------------------------------
# Sort Chronologically
# ------------------------------------------------------------

df = df.sort_values("date").reset_index(drop=True)

# ------------------------------------------------------------
# Time Series Plot
# ------------------------------------------------------------

plt.figure(figsize=(14,5))
plt.plot(df["date"], df["meantemp"])
plt.title("Mean Temperature Over Time")
plt.xlabel("Date")
plt.ylabel("Mean Temperature")
plt.grid(True)
plt.show()

# ------------------------------------------------------------
# Distribution Plots
# ------------------------------------------------------------

numeric_cols = [
    "meantemp",
    "humidity",
    "wind_speed",
    "meanpressure"
]

df[numeric_cols].hist(
    figsize=(12,8),
    bins=20
)

plt.suptitle("Variable Distributions")
plt.tight_layout()
plt.show()

# ------------------------------------------------------------
# Boxplots (Outlier Detection)
# ------------------------------------------------------------

for col in numeric_cols:

    plt.figure(figsize=(8,2))

    sns.boxplot(
        x=df[col]
    )

    plt.title(f"Boxplot of {col}")

    plt.show()

# ------------------------------------------------------------
# Correlation Matrix
# ------------------------------------------------------------

plt.figure(figsize=(8,6))

corr = df[numeric_cols].corr()

sns.heatmap(
    corr,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Correlation Matrix")
plt.show()

# ------------------------------------------------------------
# Pairplot
# ------------------------------------------------------------

sns.pairplot(df[numeric_cols])
plt.show()

# ------------------------------------------------------------
# Sweetviz Report
# ------------------------------------------------------------

sweet_report = sv.analyze(df)

sweet_report.show_html(
    "Sweetviz_Report.html"
)

print("Sweetviz report saved as Sweetviz_Report.html")

# ------------------------------------------------------------
# ydata-profiling Report
# ------------------------------------------------------------

profile = ProfileReport(
    df,
    title="Daily Delhi Climate Report",
    explorative=True
)

profile.to_file("YData_Profile_Report.html")

print("ydata-profiling report saved as YData_Profile_Report.html")

# If using Google Colab, uncomment to download the reports

# from google.colab import files
# files.download("Sweetviz_Report.html")
# files.download("YData_Profile_Report.html")

"""# Part 2. Feature Engineering and XGBoost Regression Model"""

# ============================================================
# PART 2
# Feature Engineering and XGBoost Regression Model
# ============================================================

# ------------------------------------------------------------
# Import machine learning libraries
# ------------------------------------------------------------

from sklearn.model_selection import TimeSeriesSplit
from xgboost import XGBRegressor

# ------------------------------------------------------------
# Feature Engineering
# ------------------------------------------------------------

# Create lag features (previous 7 days)

for lag in range(1, 8):
    df[f"lag_{lag}"] = df["meantemp"].shift(lag)

# ------------------------------------------------------------
# Create time-based features
# ------------------------------------------------------------

df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day
df["day_of_week"] = df["date"].dt.dayofweek
df["day_of_year"] = df["date"].dt.dayofyear
df["week_of_year"] = df["date"].dt.isocalendar().week.astype(int)

# Optional weekend indicator
df["is_weekend"] = df["day_of_week"].isin([5, 6]).astype(int)

# ------------------------------------------------------------
# Remove rows containing NaN values introduced by lag features
# ------------------------------------------------------------

df = df.dropna().reset_index(drop=True)

print("Dataset shape after creating lag features:")
print(df.shape)

display(df.head())

# ------------------------------------------------------------
# Define Feature Matrix (X) and Target Variable (y)
# ------------------------------------------------------------

feature_columns = [
    "humidity",
    "wind_speed",
    "meanpressure",
    "lag_1",
    "lag_2",
    "lag_3",
    "lag_4",
    "lag_5",
    "lag_6",
    "lag_7",
    "month",
    "day",
    "day_of_week",
    "day_of_year",
    "week_of_year",
    "is_weekend"
]

X = df[feature_columns]

y = df["meantemp"]

print("Feature matrix shape:", X.shape)
print("Target vector shape:", y.shape)

# ------------------------------------------------------------
# Chronological Train/Test Split
# ------------------------------------------------------------

train_size = int(len(df) * 0.8)

X_train = X.iloc[:train_size]
X_test = X.iloc[train_size:]

y_train = y.iloc[:train_size]
y_test = y.iloc[train_size:]

print("\nTraining samples:", len(X_train))
print("Testing samples :", len(X_test))

# ------------------------------------------------------------
# TimeSeriesSplit for Cross-Validation
# ------------------------------------------------------------

tscv = TimeSeriesSplit(n_splits=5)

print("\nTimeSeriesSplit Folds")

for fold, (train_index, val_index) in enumerate(tscv.split(X_train), start=1):

    print(f"\nFold {fold}")
    print(f"Training observations : {len(train_index)}")
    print(f"Validation observations: {len(val_index)}")

# ------------------------------------------------------------
# Build the XGBoost Regressor
# ------------------------------------------------------------

model = XGBRegressor(
    objective="reg:squarederror",
    n_estimators=300,
    learning_rate=0.05,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

# ------------------------------------------------------------
# Train the Model
# ------------------------------------------------------------

model.fit(X_train, y_train)

print("\nModel training completed successfully.")

"""# Part 3. Model Evaluation and Visualisation"""

# ============================================================
# PART 3
# Model Evaluation and Visualisation
# ============================================================

# ------------------------------------------------------------
# Import evaluation libraries
# ------------------------------------------------------------

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

from sklearn.model_selection import learning_curve

# ------------------------------------------------------------
# Make Predictions
# ------------------------------------------------------------

y_pred = model.predict(X_test)

# ------------------------------------------------------------
# Regression Metrics
# ------------------------------------------------------------

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("=" * 50)
print("Regression Performance")
print("=" * 50)
print(f"MAE : {mae:.3f}")
print(f"MSE : {mse:.3f}")
print(f"RMSE: {rmse:.3f}")
print(f"R²  : {r2:.3f}")

# ------------------------------------------------------------
# Actual vs Predicted
# ------------------------------------------------------------

plt.figure(figsize=(15,6))

plt.plot(
    y_test.values,
    label="Actual",
    linewidth=2
)

plt.plot(
    y_pred,
    label="Predicted",
    linewidth=2
)

plt.title("Actual vs Predicted Mean Temperature")
plt.xlabel("Observation")
plt.ylabel("Mean Temperature")
plt.legend()
plt.grid(True)

plt.show()

# ------------------------------------------------------------
# Residual Plot
# ------------------------------------------------------------

residuals = y_test - y_pred

plt.figure(figsize=(8,6))

plt.scatter(
    y_pred,
    residuals,
    alpha=0.7
)

plt.axhline(
    y=0,
    color="red",
    linestyle="--"
)

plt.xlabel("Predicted Values")
plt.ylabel("Residuals")
plt.title("Residual Plot")

plt.show()

# ------------------------------------------------------------
# Feature Importance
# ------------------------------------------------------------

importance = pd.DataFrame({

    "Feature": feature_columns,
    "Importance": model.feature_importances_

})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

display(importance)

plt.figure(figsize=(10,6))

sns.barplot(
    data=importance,
    x="Importance",
    y="Feature"
)

plt.title("Feature Importance")

plt.show()

# ------------------------------------------------------------
# Learning Curve using TimeSeriesSplit
# ------------------------------------------------------------

train_sizes, train_scores, validation_scores = learning_curve(

    estimator=model,

    X=X_train,

    y=y_train,

    cv=tscv,

    scoring="neg_mean_squared_error",

    train_sizes=np.linspace(0.2, 1.0, 5),

    n_jobs=-1

)

train_scores = np.sqrt(-train_scores)
validation_scores = np.sqrt(-validation_scores)

train_mean = train_scores.mean(axis=1)
validation_mean = validation_scores.mean(axis=1)

plt.figure(figsize=(10,6))

plt.plot(
    train_sizes,
    train_mean,
    marker="o",
    label="Training RMSE"
)

plt.plot(
    train_sizes,
    validation_mean,
    marker="o",
    label="Validation RMSE"
)

plt.title("Learning Curve")
plt.xlabel("Training Examples")
plt.ylabel("RMSE")
plt.legend()
plt.grid(True)

plt.show()

# ------------------------------------------------------------
# Interpretation
# ------------------------------------------------------------

print("\nModel Interpretation")
print("-" * 60)

print(f"Mean Absolute Error : {mae:.3f}")
print(f"Root Mean Squared Error : {rmse:.3f}")
print(f"R² Score : {r2:.3f}")

if r2 >= 0.90:
    print("\nThe model explains most of the variation in the temperature data.")
elif r2 >= 0.70:
    print("\nThe model provides a reasonably good fit to the data.")
else:
    print("\nThe model has limited predictive performance and may benefit from additional feature engineering or parameter tuning.")

print("\nLearning Curve Interpretation:")

gap = validation_mean[-1] - train_mean[-1]

if gap > 2:
    print("The validation error remains noticeably higher than the training error, suggesting possible overfitting.")
elif abs(gap) < 0.5:
    print("Training and validation errors are similar, suggesting good generalisation.")
else:
    print("The model may benefit from additional training data or hyperparameter tuning.")
